project:
  type: website
  output-dir: docs

website:
  title: "Data Vizulizations 334 Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mhein804
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css



